// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoccerClubPlayerManagement.Data;

#nullable disable

namespace SoccerClubPlayerManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261001112034_AddBallControlTrait")]
    partial class AddBallControlTrait
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Formation", b =>
                {
                    b.Property<int>("FormationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("FormationId");

                    b.ToTable("Formations");

                    b.HasData(
                        new
                        {
                            FormationId = 1,
                            Name = "4-4-2"
                        },
                        new
                        {
                            FormationId = 2,
                            Name = "4-3-3"
                        },
                        new
                        {
                            FormationId = 3,
                            Name = "3-5-2"
                        },
                        new
                        {
                            FormationId = 4,
                            Name = "4-2-3-1"
                        });
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.FormationSlot", b =>
                {
                    b.Property<int>("FormationSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormationSlotId"));

                    b.Property<int>("FormationId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SlotOrder")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("FormationSlotId");

                    b.HasIndex("FormationId");

                    b.ToTable("FormationSlots");

                    b.HasData(
                        new
                        {
                            FormationSlotId = 1,
                            FormationId = 1,
                            Label = "GK",
                            SlotOrder = 1,
                            X = 50,
                            Y = 95
                        },
                        new
                        {
                            FormationSlotId = 2,
                            FormationId = 1,
                            Label = "LB",
                            SlotOrder = 2,
                            X = 15,
                            Y = 75
                        },
                        new
                        {
                            FormationSlotId = 3,
                            FormationId = 1,
                            Label = "CB",
                            SlotOrder = 3,
                            X = 35,
                            Y = 80
                        },
                        new
                        {
                            FormationSlotId = 4,
                            FormationId = 1,
                            Label = "CB",
                            SlotOrder = 4,
                            X = 65,
                            Y = 80
                        },
                        new
                        {
                            FormationSlotId = 5,
                            FormationId = 1,
                            Label = "RB",
                            SlotOrder = 5,
                            X = 85,
                            Y = 75
                        },
                        new
                        {
                            FormationSlotId = 6,
                            FormationId = 1,
                            Label = "LM",
                            SlotOrder = 6,
                            X = 15,
                            Y = 45
                        },
                        new
                        {
                            FormationSlotId = 7,
                            FormationId = 1,
                            Label = "CM",
                            SlotOrder = 7,
                            X = 35,
                            Y = 50
                        },
                        new
                        {
                            FormationSlotId = 8,
                            FormationId = 1,
                            Label = "CM",
                            SlotOrder = 8,
                            X = 65,
                            Y = 50
                        },
                        new
                        {
                            FormationSlotId = 9,
                            FormationId = 1,
                            Label = "RM",
                            SlotOrder = 9,
                            X = 85,
                            Y = 45
                        },
                        new
                        {
                            FormationSlotId = 10,
                            FormationId = 1,
                            Label = "ST",
                            SlotOrder = 10,
                            X = 35,
                            Y = 15
                        },
                        new
                        {
                            FormationSlotId = 11,
                            FormationId = 1,
                            Label = "ST",
                            SlotOrder = 11,
                            X = 65,
                            Y = 15
                        },
                        new
                        {
                            FormationSlotId = 12,
                            FormationId = 2,
                            Label = "GK",
                            SlotOrder = 1,
                            X = 50,
                            Y = 95
                        },
                        new
                        {
                            FormationSlotId = 13,
                            FormationId = 2,
                            Label = "LB",
                            SlotOrder = 2,
                            X = 15,
                            Y = 75
                        },
                        new
                        {
                            FormationSlotId = 14,
                            FormationId = 2,
                            Label = "CB",
                            SlotOrder = 3,
                            X = 35,
                            Y = 80
                        },
                        new
                        {
                            FormationSlotId = 15,
                            FormationId = 2,
                            Label = "CB",
                            SlotOrder = 4,
                            X = 65,
                            Y = 80
                        },
                        new
                        {
                            FormationSlotId = 16,
                            FormationId = 2,
                            Label = "RB",
                            SlotOrder = 5,
                            X = 85,
                            Y = 75
                        },
                        new
                        {
                            FormationSlotId = 17,
                            FormationId = 2,
                            Label = "CM",
                            SlotOrder = 6,
                            X = 30,
                            Y = 50
                        },
                        new
                        {
                            FormationSlotId = 18,
                            FormationId = 2,
                            Label = "CM",
                            SlotOrder = 7,
                            X = 50,
                            Y = 55
                        },
                        new
                        {
                            FormationSlotId = 19,
                            FormationId = 2,
                            Label = "CM",
                            SlotOrder = 8,
                            X = 70,
                            Y = 50
                        },
                        new
                        {
                            FormationSlotId = 20,
                            FormationId = 2,
                            Label = "LW",
                            SlotOrder = 9,
                            X = 15,
                            Y = 20
                        },
                        new
                        {
                            FormationSlotId = 21,
                            FormationId = 2,
                            Label = "ST",
                            SlotOrder = 10,
                            X = 50,
                            Y = 10
                        },
                        new
                        {
                            FormationSlotId = 22,
                            FormationId = 2,
                            Label = "RW",
                            SlotOrder = 11,
                            X = 85,
                            Y = 20
                        },
                        new
                        {
                            FormationSlotId = 23,
                            FormationId = 3,
                            Label = "GK",
                            SlotOrder = 1,
                            X = 50,
                            Y = 95
                        },
                        new
                        {
                            FormationSlotId = 24,
                            FormationId = 3,
                            Label = "CB",
                            SlotOrder = 2,
                            X = 30,
                            Y = 80
                        },
                        new
                        {
                            FormationSlotId = 25,
                            FormationId = 3,
                            Label = "CB",
                            SlotOrder = 3,
                            X = 50,
                            Y = 85
                        },
                        new
                        {
                            FormationSlotId = 26,
                            FormationId = 3,
                            Label = "CB",
                            SlotOrder = 4,
                            X = 70,
                            Y = 80
                        },
                        new
                        {
                            FormationSlotId = 27,
                            FormationId = 3,
                            Label = "LM",
                            SlotOrder = 5,
                            X = 10,
                            Y = 50
                        },
                        new
                        {
                            FormationSlotId = 28,
                            FormationId = 3,
                            Label = "CM",
                            SlotOrder = 6,
                            X = 35,
                            Y = 55
                        },
                        new
                        {
                            FormationSlotId = 29,
                            FormationId = 3,
                            Label = "CM",
                            SlotOrder = 7,
                            X = 50,
                            Y = 60
                        },
                        new
                        {
                            FormationSlotId = 30,
                            FormationId = 3,
                            Label = "CM",
                            SlotOrder = 8,
                            X = 65,
                            Y = 55
                        },
                        new
                        {
                            FormationSlotId = 31,
                            FormationId = 3,
                            Label = "RM",
                            SlotOrder = 9,
                            X = 90,
                            Y = 50
                        },
                        new
                        {
                            FormationSlotId = 32,
                            FormationId = 3,
                            Label = "ST",
                            SlotOrder = 10,
                            X = 35,
                            Y = 15
                        },
                        new
                        {
                            FormationSlotId = 33,
                            FormationId = 3,
                            Label = "ST",
                            SlotOrder = 11,
                            X = 65,
                            Y = 15
                        },
                        new
                        {
                            FormationSlotId = 34,
                            FormationId = 4,
                            Label = "GK",
                            SlotOrder = 1,
                            X = 50,
                            Y = 95
                        },
                        new
                        {
                            FormationSlotId = 35,
                            FormationId = 4,
                            Label = "LB",
                            SlotOrder = 2,
                            X = 15,
                            Y = 75
                        },
                        new
                        {
                            FormationSlotId = 36,
                            FormationId = 4,
                            Label = "CB",
                            SlotOrder = 3,
                            X = 35,
                            Y = 80
                        },
                        new
                        {
                            FormationSlotId = 37,
                            FormationId = 4,
                            Label = "CB",
                            SlotOrder = 4,
                            X = 65,
                            Y = 80
                        },
                        new
                        {
                            FormationSlotId = 38,
                            FormationId = 4,
                            Label = "RB",
                            SlotOrder = 5,
                            X = 85,
                            Y = 75
                        },
                        new
                        {
                            FormationSlotId = 39,
                            FormationId = 4,
                            Label = "CDM",
                            SlotOrder = 6,
                            X = 35,
                            Y = 60
                        },
                        new
                        {
                            FormationSlotId = 40,
                            FormationId = 4,
                            Label = "CDM",
                            SlotOrder = 7,
                            X = 65,
                            Y = 60
                        },
                        new
                        {
                            FormationSlotId = 41,
                            FormationId = 4,
                            Label = "LW",
                            SlotOrder = 8,
                            X = 15,
                            Y = 35
                        },
                        new
                        {
                            FormationSlotId = 42,
                            FormationId = 4,
                            Label = "CAM",
                            SlotOrder = 9,
                            X = 50,
                            Y = 30
                        },
                        new
                        {
                            FormationSlotId = 43,
                            FormationId = 4,
                            Label = "RW",
                            SlotOrder = 10,
                            X = 85,
                            Y = 35
                        },
                        new
                        {
                            FormationSlotId = 44,
                            FormationId = 4,
                            Label = "ST",
                            SlotOrder = 11,
                            X = 50,
                            Y = 10
                        });
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Lineup", b =>
                {
                    b.Property<int>("LineupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineupId"));

                    b.Property<int?>("CaptainPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("CoachName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FormationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LineupId");

                    b.HasIndex("CaptainPlayerId");

                    b.HasIndex("FormationId");

                    b.ToTable("Lineups");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.LineupSlot", b =>
                {
                    b.Property<int>("LineupSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineupSlotId"));

                    b.Property<int>("FormationSlotId")
                        .HasColumnType("int");

                    b.Property<int>("LineupId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("LineupSlotId");

                    b.HasIndex("FormationSlotId");

                    b.HasIndex("LineupId");

                    b.HasIndex("PlayerId");

                    b.ToTable("LineupSlots");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.LineupSubstitute", b =>
                {
                    b.Property<int>("LineupSubstituteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineupSubstituteId"));

                    b.Property<int>("LineupId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SubOrder")
                        .HasColumnType("int");

                    b.HasKey("LineupSubstituteId");

                    b.HasIndex("LineupId");

                    b.HasIndex("PlayerId");

                    b.ToTable("LineupSubstitutes");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HeightFeet")
                        .HasColumnType("int");

                    b.Property<int?>("HeightInches")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int?>("PreferredFoot")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("PositionId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.PlayerTrait", b =>
                {
                    b.Property<int>("PlayerTraitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerTraitId"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TraitId")
                        .HasColumnType("int");

                    b.HasKey("PlayerTraitId");

                    b.HasIndex("TraitId");

                    b.HasIndex("PlayerId", "TraitId")
                        .IsUnique();

                    b.ToTable("PlayerTraits");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = 1,
                            Name = "Goalkeeper"
                        },
                        new
                        {
                            PositionId = 2,
                            Name = "Defender"
                        },
                        new
                        {
                            PositionId = 3,
                            Name = "Midfielder"
                        },
                        new
                        {
                            PositionId = 4,
                            Name = "Forward"
                        });
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Trait", b =>
                {
                    b.Property<int>("TraitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraitId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("TraitId");

                    b.HasIndex("PositionId");

                    b.ToTable("Traits");

                    b.HasData(
                        new
                        {
                            TraitId = 1,
                            Name = "Pace"
                        },
                        new
                        {
                            TraitId = 2,
                            Name = "Stamina"
                        },
                        new
                        {
                            TraitId = 3,
                            Name = "Leadership"
                        },
                        new
                        {
                            TraitId = 4,
                            Name = "Finishing"
                        },
                        new
                        {
                            TraitId = 5,
                            Name = "Passing"
                        },
                        new
                        {
                            TraitId = 6,
                            Name = "Tackling"
                        },
                        new
                        {
                            TraitId = 7,
                            Name = "Marking"
                        },
                        new
                        {
                            TraitId = 8,
                            Name = "Heading"
                        },
                        new
                        {
                            TraitId = 9,
                            Name = "Agility"
                        },
                        new
                        {
                            TraitId = 10,
                            Name = "Vision"
                        },
                        new
                        {
                            TraitId = 11,
                            Name = "Skill Moves"
                        },
                        new
                        {
                            TraitId = 16,
                            Name = "Ball Control"
                        },
                        new
                        {
                            TraitId = 12,
                            Name = "Diving",
                            PositionId = 1
                        },
                        new
                        {
                            TraitId = 13,
                            Name = "Reflexes",
                            PositionId = 1
                        },
                        new
                        {
                            TraitId = 14,
                            Name = "Handling",
                            PositionId = 1
                        },
                        new
                        {
                            TraitId = 15,
                            Name = "Distribution",
                            PositionId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SoccerClubPlayerManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SoccerClubPlayerManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerClubPlayerManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SoccerClubPlayerManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.FormationSlot", b =>
                {
                    b.HasOne("SoccerClubPlayerManagement.Models.Formation", "Formation")
                        .WithMany("Slots")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Lineup", b =>
                {
                    b.HasOne("SoccerClubPlayerManagement.Models.Player", "Captain")
                        .WithMany()
                        .HasForeignKey("CaptainPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoccerClubPlayerManagement.Models.Formation", "Formation")
                        .WithMany()
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Captain");

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.LineupSlot", b =>
                {
                    b.HasOne("SoccerClubPlayerManagement.Models.FormationSlot", "FormationSlot")
                        .WithMany()
                        .HasForeignKey("FormationSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoccerClubPlayerManagement.Models.Lineup", "Lineup")
                        .WithMany("LineupSlots")
                        .HasForeignKey("LineupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerClubPlayerManagement.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FormationSlot");

                    b.Navigation("Lineup");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.LineupSubstitute", b =>
                {
                    b.HasOne("SoccerClubPlayerManagement.Models.Lineup", "Lineup")
                        .WithMany("Substitutes")
                        .HasForeignKey("LineupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerClubPlayerManagement.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lineup");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Player", b =>
                {
                    b.HasOne("SoccerClubPlayerManagement.Models.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.PlayerTrait", b =>
                {
                    b.HasOne("SoccerClubPlayerManagement.Models.Player", "Player")
                        .WithMany("PlayerTraits")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerClubPlayerManagement.Models.Trait", "Trait")
                        .WithMany("PlayerTraits")
                        .HasForeignKey("TraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Trait");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Trait", b =>
                {
                    b.HasOne("SoccerClubPlayerManagement.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Position");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Formation", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Lineup", b =>
                {
                    b.Navigation("LineupSlots");

                    b.Navigation("Substitutes");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Player", b =>
                {
                    b.Navigation("PlayerTraits");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Position", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Trait", b =>
                {
                    b.Navigation("PlayerTraits");
                });
#pragma warning restore 612, 618
        }
    }
}
