// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoccerClubPlayerManagement.Data;

#nullable disable

namespace SoccerClubPlayerManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260926173319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("PositionId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.PlayerTrait", b =>
                {
                    b.Property<int>("PlayerTraitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerTraitId"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TraitId")
                        .HasColumnType("int");

                    b.HasKey("PlayerTraitId");

                    b.HasIndex("TraitId");

                    b.HasIndex("PlayerId", "TraitId")
                        .IsUnique();

                    b.ToTable("PlayerTraits");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = 1,
                            Name = "Goalkeeper"
                        },
                        new
                        {
                            PositionId = 2,
                            Name = "Defender"
                        },
                        new
                        {
                            PositionId = 3,
                            Name = "Midfielder"
                        },
                        new
                        {
                            PositionId = 4,
                            Name = "Forward"
                        });
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Trait", b =>
                {
                    b.Property<int>("TraitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraitId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TraitId");

                    b.ToTable("Traits");

                    b.HasData(
                        new
                        {
                            TraitId = 1,
                            Name = "Pace"
                        },
                        new
                        {
                            TraitId = 2,
                            Name = "Stamina"
                        },
                        new
                        {
                            TraitId = 3,
                            Name = "Leadership"
                        },
                        new
                        {
                            TraitId = 4,
                            Name = "Finishing"
                        },
                        new
                        {
                            TraitId = 5,
                            Name = "Passing"
                        });
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Player", b =>
                {
                    b.HasOne("SoccerClubPlayerManagement.Models.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.PlayerTrait", b =>
                {
                    b.HasOne("SoccerClubPlayerManagement.Models.Player", "Player")
                        .WithMany("PlayerTraits")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerClubPlayerManagement.Models.Trait", "Trait")
                        .WithMany("PlayerTraits")
                        .HasForeignKey("TraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Trait");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Player", b =>
                {
                    b.Navigation("PlayerTraits");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Position", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("SoccerClubPlayerManagement.Models.Trait", b =>
                {
                    b.Navigation("PlayerTraits");
                });
#pragma warning restore 612, 618
        }
    }
}
